"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {render,pct,renderTopicPregen,diagnosticPanel}=require("./app.js");
function dom(){const els=new Map();global.document={getElementById(id){if(!els.has(id))els.set(id,{innerHTML:"",textContent:"",hidden:true,className:""});return els.get(id);}};return els;}
function fixture(){return{generatedAt:"2026-09-25T00:00:00Z",overall:{status:"normal"},connections:{supabase:{status:"ok",error:null},redis:{status:"error",error:{type:"Error",code:"ECONNRESET",httpStatus:null}}},period:{since:"2026-09-24T00:00:00Z",todayStart:"2026-09-24T15:00:00Z"},topic:{stage1:{models:[{model:"qwen/qwen3.8-27b",success:null,failed:null,fallback:null},{model:"openai/gpt-oss-20b",success:null,failed:null,fallback:null}]},topicSearch:{currentMode:null,lastObservedMode:"upstash",lastObservedVersion:"openai/text-embedding-3-small:1536:v1",lastObservedAt:"2026-09-24T23:00:00Z",upstash:{successfulCommits:2,failures:null},providerUnattributedFailures:1},total:1,logRows:2,outcomes:{new_topic:{count:1},merged:{count:0},excluded:{count:0},failed_gemma:{count:0},failed_embedding:{count:0},failed_search:{count:0},failed_db:{count:0}},fallback:{count:null,rate:null,denominator:1},articleBody:{loggedFailures:0},gemma:{stage1:{total:1,success:1,failed:0,successRate:1,failureRate:0,httpFailures:{},averageDurationMs:12,p95DurationMs:12,promptTokens:10,outputTokens:4,thinkingTokens:0},stage2:{total:0,success:0,failed:0,successRate:null,failureRate:null,httpFailures:{},averageDurationMs:null,p95DurationMs:null,promptTokens:0,outputTokens:0,thinkingTokens:0},repetitionLoop:0,maxTokens:0,invalid:0,timeoutNetwork:0,http429:0,http5xx:0,failuresByReason:{}},embedding:{byModelVersion:[{model:"model-a",version:"version-1",count:4,failures:1}],averageSimilarity:.82,similarityCount:3,failureReasons:{timeout:1},quota:{status:"ok",models:[{model:"model-a",quotaDayPt:"2026-09-24",usedToday:4,exhausted:false,resetProbeStartedAt:null,firstSuccessAfterReset:null,updatedAt:null}]}},quality:{factsSuccess:1,factsZero:0,threadTitleSuccess:1,threadTitleFailed:1,threadTitlePending:0,threadTitleProcessing:0,threadTitleSet:1,threadTitleFailureReasons:{timeout:1},threadTitleBatchFailureReasons:{http_5xx:1},threadTitleBatchCount:2,threadTitleTokens:{input:12,output:3,thinking:2},threadTitleBatchDurationMs:[100,200],threadTitleQuotaSummary:[{model:"title-model",quotaDayPt:"2026-09-24",latestUsedToday:5,httpStatusCounts:{200:1},probeCount:0}],threadTitleQuota:[{model:"title-model",quotaDayPt:"2026-09-24",usedTodayAtRequest:5,probe:false,httpStatus:200}] }},topicVectorOutbox:{status:"ok",pending:0,processing:1,staleClaimed:1,syncFailures:null},newsdata:null,rss:null,infrastructure:{failedDb:0,lastNormalDbAt:null,cronEstimate:"scheduler unavailable",redisLastSuccessAt:null},anomalies:[]};}
test("日本語名称と構造化テーブルを表示し、生JSONを表示しない",()=>{const els=dom();render(fixture());assert.match(els.get("connections").innerHTML,/集計期間/);assert.match(els.get("embedding").innerHTML,/model-a/);assert.match(els.get("embedding").innerHTML,/timeout/);assert.match(els.get("quality").innerHTML,/失敗理由（Topic単位）/);assert.match(els.get("quality").innerHTML,/所要時間の平均/);assert.match(els.get("quality").innerHTML,/<details>/);assert.doesNotMatch(els.get("embedding").innerHTML,/\{"/);assert.doesNotMatch(els.get("quality").innerHTML,/\{"/);assert.match(els.get("infrastructure").innerHTML,/NewsData定期処理/);});
test("Stage 1/2を役割名で表示し、空データは空見出しを作らない",()=>{const els=dom(),data=fixture();render(data);assert.match(els.get("gemma").innerHTML,/記事の分類/);assert.match(els.get("gemma").innerHTML,/記事からの事実抽出/);data.topic.gemma.stage1.total=0;data.topic.gemma.stage2.total=0;render(data);assert.doesNotMatch(els.get("gemma").innerHTML,/記事の分類|記事からの事実抽出/);assert.match(els.get("gemma").innerHTML,/この期間にAI分析の試行記録はありません/);});
test("Stage analysis shows deployment windows with separate Stage and API-attempt counts",()=>{const els=dom(),data=fixture();data.topic.releaseAudit=[{version:"v83",from:"2026-09-28T23:13:48Z",to:"2026-09-29T00:21:52Z",stage1:{success:10,failed:1},stage1Attempts:12,stage1QuotaBlocked:2,stage2:{success:8,failed:0},titleTopics:{success:4,failed:0,pending:0},titleBatchCount:1,titleApiAttempts:2}];render(data);assert.match(els.get("gemma").innerHTML,/配備版別/);assert.match(els.get("gemma").innerHTML,/v83/);assert.match(els.get("gemma").innerHTML,/12 \/ 2/);});
test("未計測の割合を0%として表示しない",()=>{assert.equal(pct(null,10),"未計測");assert.equal(pct(0,10),"0.0%");const els=dom();render(fixture());assert.match(els.get("topic").innerHTML,/判定失敗時に単独作成/);assert.match(els.get("topic").innerHTML,/割合 未計測/);});
test("接続失敗の詳細を表示する",()=>{const els=dom(),data=fixture();data.overall.status="unavailable";render(data);assert.match(els.get("connections").innerHTML,/ECONNRESET/);assert.match(els.get("summary").textContent,/接続失敗/);});
test("モデル未記録と混在モデルの表示を保持する",()=>{const els=dom(),data=fixture();data.topic.embedding.byModelVersion.push({model:null,version:"v2",count:2,failures:0},{model:"model-b",version:"v2",count:1,failures:1});render(data);assert.match(els.get("embedding").innerHTML,/モデル未記録/);assert.match(els.get("embedding").innerHTML,/model-b/);});

test("事前生成モニターにtargetと再試行・保存状態を表示する",()=>{const els=dom();renderTopicPregen({available:true,fetchedAt:"2026-09-25T08:00:00Z",state:{targetTopicId:"38fd9edf-5d7d-4449-aae9-b4d390d3a259",generation:3,status:"retry_wait",attempts:4,rollingWindowAttempts:2,lastHttpStatus:503,lastErrorMessage:"Invalid setting <script>",lastErrorType:"http_error",retryNotBefore:1790320000000,alarmScheduled:true,alarmAt:1790320000000,parserSucceeded:null,saveAttempted:false,saveSucceeded:null,lastProcessedAt:1790319000000}});const html=els.get("pregen").innerHTML;assert.match(html,/38fd9edf/);assert.match(html,/再試行待ち/);assert.doesNotMatch(html,/503/);assert.match(els.get("anomalies").innerHTML,/503/);assert.match(els.get("anomalies").innerHTML,/Invalid setting &lt;script&gt;/);assert.doesNotMatch(els.get("anomalies").innerHTML,/<script>/);assert.match(els.get("anomalies").innerHTML,/diagnostic-technical/);assert.match(els.get("pregen-fetched-at").textContent,/最終取得/);});

test("事前生成モニターは診断API取得失敗と取得日時を表示する",()=>{const els=dom();renderTopicPregen({available:false,fetchedAt:"2026-09-25T08:00:00Z",error:{type:"http_error",httpStatus:403}});assert.match(els.get("pregen").innerHTML,/監視情報を取得できません/);assert.match(els.get("anomalies").innerHTML,/403/);assert.match(els.get("pregen-fetched-at").textContent,/最終取得/);});

test("31B診断GETは手動ボタンだけで実行し、自動ポーリングしない",async()=>{const oldDocument=global.document,oldFetch=global.fetch,modulePath=require.resolve("./app.js"),callbacks=new Map(),els=dom(),calls=[];for(const id of ["refresh","refresh-pregen"])global.document.getElementById(id).addEventListener=(_event,handler)=>callbacks.set(id,handler);global.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>url==="/api/dashboard"?fixture():{available:true,fetchedAt:"2026-09-25T08:00:00Z",state:{status:"completed",targetTopicId:null,generation:1,attempts:1}}};};delete require.cache[modulePath];try{require("./app.js");await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls,["/api/dashboard"]);await callbacks.get("refresh-pregen")();assert.deepEqual(calls,["/api/dashboard","/api/topic-pregen"]);}finally{delete require.cache[modulePath];global.document=oldDocument;global.fetch=oldFetch;}});

test("Operations distinguishes recorded Topic search from unavailable mode and failure metrics",()=>{const els=dom();render(fixture());const html=els.get("topic-vector").innerHTML;assert.match(html,/現在の検索モード/);assert.match(html,/未記録（Supabase Secretは参照していません）/);assert.match(html,/最終成功ログから観測した検索元/);assert.match(html,/未計測/);assert.match(html,/Upstash検索API成功/);assert.match(html,/Outbox処理中/);assert.match(html,/15分超のclaim/);assert.match(els.get("gemma").innerHTML,/Stage 1（記事の分類・provider未記録を含む）/);assert.match(els.get("gemma").innerHTML,/fallback/);assert.match(els.get("embedding").innerHTML,/Gemini Embedding利用枠履歴/);});
test("outbox zero is distinct from unavailable and legacy Stage 1 is not labeled Groq",()=>{const els=dom(),data=fixture();data.topicVectorOutbox={status:"ok",pending:0,processing:0,staleClaimed:0,syncFailures:null};render(data);const vector=els.get("topic-vector").innerHTML;assert.match(vector,/Outbox未処理/);assert.match(vector,/<b class="">0/);assert.match(vector,/同期失敗/);assert.match(vector,/未計測/);assert.match(els.get("gemma").innerHTML,/Stage 1・Groq候補モデル/);assert.doesNotMatch(els.get("gemma").innerHTML,/Groq Stage 1/);data.topicVectorOutbox={status:"unavailable",pending:null,processing:null,staleClaimed:null,syncFailures:null,readError:{type:"Error",httpStatus:503}};render(data);assert.match(els.get("topic-vector").innerHTML,/Error \/ HTTP 503/);});test("Upstash commit counts are not labeled as search successes",()=>{const els=dom();render(fixture());const html=els.get("topic-vector").innerHTML;assert.match(html,/Upstash検索API成功/);assert.match(html,/Upstash検索API成功/);assert.match(html,/Outbox同期失敗/);assert.match(html,/成功commitと検索API成功は別集計です/);});
test("Operations renders model-level attempts, search API timings and outbox sync outcomes separately",()=>{const els=dom(),data=fixture();data.topic.stage1.models=[{model:"qwen/qwen3.8-27b",attempts:2,success:0,failed:2,timeoutRetries:1,fallback:0},{model:"openai/gpt-oss-20b",attempts:1,success:1,failed:0,timeoutRetries:0,fallback:1}];data.topic.stage1.fallbackReasons={timeout:1};data.topic.stage1.unattributedStageRecords=17;Object.assign(data.topic.topicSearch.upstash,{searchSuccesses:4,searchFailures:1,searchAverageDurationMs:28,searchP95DurationMs:41,searchFailureReasons:{http_401:1},searchByEmbeddingVersion:[{version:"openai/text-embedding-3-small:1536:v1",successes:4,failures:1}],newTopicCommits:3,mergeCommits:1});Object.assign(data.topicVectorOutbox,{syncSuccesses:2,syncedRecords:7,syncFailures:1,lastSyncSuccessAt:"2026-09-24T23:00:00Z",lastSyncFailureAt:"2026-09-24T23:10:00Z",failureReasons:{http_503:1},observationStatus:"ok"});render(data);const stage=els.get("gemma").innerHTML,vector=els.get("topic-vector").innerHTML;assert.match(stage,/API試行/);assert.match(stage,/timeout再試行/);assert.match(stage,/fallback理由/);assert.match(stage,/17 Stage記録/);assert.match(vector,/Upstash検索API成功/);assert.match(vector,/Upstash検索時間 平均 \/ p95/);assert.match(vector,/Upstash新規Topic commit/);assert.match(vector,/Upstash既存Topic merge/);assert.match(vector,/Outbox同期成功batch/);assert.match(vector,/最終同期失敗/);assert.match(vector,/http_503/);});

test("common diagnostic panel keeps details collapsed and escapes developer fields",()=>{const els=dom();const html=diagnosticPanel([{feature:"Article body",errorTypes:["http_403"],errorCount:1,lastOccurredAt:"2026-09-20T00:00:00Z",currentState:"未解決",classification:"要対応",events:[{what:"HTTP failure",errorType:"http_403",occurredAt:"2026-09-20T00:00:00Z",stage:"article_body",confirmedCause:null,identifiers:{articleId:"article-1"},httpStatus:403,retry:null,finalResult:null,classification:"要対応",developerDetails:{safe:"<script>"}}]}]);assert.match(html,/diagnostic-feature/);assert.match(html,/article-1/);assert.match(html,/HTTP failure/);assert.match(html,/開発者向け詳細/);assert.doesNotMatch(html,/<details class="diagnostic-feature" open/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);});

test("expanded body diagnostics show missing legacy fields explicitly and keep technical detail nested",()=>{const html=diagnosticPanel([{feature:"記事本文取得",errorTypes:["readability_failed"],errorCount:1,lastOccurredAt:"2026-09-29T08:00:00Z",currentState:"未解決",classification:"要対応",events:[{what:"記事本文取得に失敗",errorType:"readability_failed",occurredAt:"2026-09-29T08:00:00Z",stage:"article_body",confirmedCause:"readability_failed",identifiers:{articleId:"sha256:abc123"},httpStatus:null,retry:null,finalResult:"excluded_invalid_article",classification:"要対応",displayDetails:{domain:null,finalDomain:"news.example",domParse:"success",readability:"failed",finalExclusionReason:"excluded_invalid_article"},developerDetails:{}}]}]);assert.match(html,/取得先ドメイン/);assert.match(html,/未記録/);assert.match(html,/最終URLドメイン/);assert.match(html,/news\.example/);assert.doesNotMatch(html,/<details class="diagnostic-technical" open/);});
test("diagnostic panel uses compact type badges and dark high-contrast surfaces",()=>{
 const html=diagnosticPanel([{feature:"Stage 2 / Gemma 4 26B",errorTypes:["http_500","timeout"],errorCount:2,lastOccurredAt:"2026-09-29T10:07:02Z",currentState:"unresolved",classification:"\u8981\u5bfe\u5fdc",events:[{what:"HTTP 500",errorType:"http_500",occurredAt:"2026-09-29T10:07:02Z",stage:"stage2_attempt",classification:"\u8981\u5bfe\u5fdc",developerDetails:{provider:"google",httpStatus:500}}]}]);
 assert.equal((html.match(/class="diagnostic-error-type"/g)||[]).length,2);
 assert.match(html,/diagnostic-types/);assert.match(html,/diagnostic-count/);assert.match(html,/diagnostic-class action/);assert.match(html,/<details class="diagnostic-feature"/);assert.match(html,/<details class="diagnostic-event"/);assert.doesNotMatch(html,/<details class="diagnostic-feature" open/);
 const css=require("node:fs").readFileSync(require("node:path").join(__dirname,"style.css"),"utf8");
 assert.doesNotMatch(css,/var\(--surface,#fff\)/);
 assert.match(css,/.diagnostic-feature,.diagnostic-event,.diagnostic-technical,.developer-details\{border:1px solid #34445b;border-radius:.65rem;background:#121a27;color:#edf2f7\}/);
 assert.ok(css.includes("color:#e6edf7"));assert.ok(css.includes("color:#e6edf7"));
 assert.match(css,/.diagnostic-class\.action\{color:#fecaca;background:#3b1d24/);assert.match(css,/.diagnostic-class\.past\{color:#fed7aa;background:#3a2b1b/);assert.match(css,/.diagnostic-class\.watch\{color:#bfdbfe;background:#1d2e45/);assert.match(css,/.diagnostic-class\.normal\{color:#bbf7d0;background:#173326/);
 assert.match(css,/.developer-details pre\{[^\}]*background:#0b111b;color:#e2e8f0/);assert.match(css,/max-width:650px/);assert.match(css,/.diagnostic-types\{flex-basis:100%\}/);
});
test("Stage 2 retry diagnostics and deferred queue schedule are visible in the dashboard",()=>{
 const html=diagnosticPanel([
  {feature:"Stage 2 / Gemma 4 26B",errorTypes:["http_500"],errorCount:1,lastOccurredAt:"2026-09-29T10:00:00Z",currentState:"retry後成功",classification:"経過観察",events:[{what:"Stage 2で失敗",errorType:"http_500",occurredAt:"2026-09-29T10:00:00Z",stage:"stage2_attempt",httpStatus:500,retry:"1回",finalResult:"retry後成功・最終HTTP 200",classification:"経過観察",displayDetails:{retryCount:1,firstHttpError:"HTTP 500 http_500",finalHttpStatus:200,quotaRetryStopped:false,rateLimitType:null,scheduledAt:null},developerDetails:{}}]},
  {feature:"Topic processing queue",errorTypes:["stage2_retry_scheduled"],errorCount:1,lastOccurredAt:"2026-09-29T12:00:00Z",currentState:"次回処理予定",classification:"経過観察",events:[{what:"Stage 2 retryを延期しています",errorType:"stage2_retry_scheduled",occurredAt:"2026-09-29T12:00:00Z",stage:"stage2_deferred_retry",retry:"queueの次回処理予定",finalResult:"次回処理予定 2026-09-29T12:00:00Z",classification:"経過観察",displayDetails:{deferredCount:1,nextScheduledAt:"2026-09-29T12:00:00Z"},developerDetails:{}}]},
 ]);
 assert.match(html,/初回HTTPエラー/);assert.match(html,/HTTP 500 http_500/);assert.match(html,/最終HTTP status/);assert.match(html,/retry回数/);assert.match(html,/quotaによるretry停止/);assert.match(html,/Stage 2延期件数/);assert.match(html,/次回処理予定/);assert.match(html,/2026-09-29T12:00:00Z/);
});
test("quota diagnostic events display the limiter time window",()=>{
 const html=diagnosticPanel([{feature:"Stage 1",errorTypes:["quota_limit"],errorCount:1,lastOccurredAt:"2026-09-29T10:00:00Z",currentState:"未解決",classification:"要対応",events:[{what:"stage1_attemptで失敗",errorType:"quota_limit",occurredAt:"2026-09-29T10:00:00Z",stage:"stage1_attempt",confirmedCause:"quota_limit",displayDetails:{quotaReason:"quota_limit",quotaAxis:"tpm",quotaWindow:"60s rolling",quotaLimit:16000,quotaUsed:0,quotaRequested:63100,quotaReserved:0},developerDetails:{}}]}]);
 assert.match(html,/quota停止理由/);assert.match(html,/今回要求量/);assert.match(html,/63100/);assert.match(html,/制限時間窓/);assert.match(html,/60s rolling/);assert.match(html,/判定時使用量/);
});
