"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {aggregateTopics,aggregateNewsData,jstTodayStart,percentile,supabaseTopicRows,supabaseTopicVectorOutbox}=require("./server.js");
test("JST day boundary",()=>assert.equal(jstTodayStart(new Date("2026-09-19T16:00:00Z")).toISOString(),"2026-09-19T15:00:00.000Z"));
test("article outcomes use latest final row per article",()=>{const b={article_id:"a",created_at:"2026-09-20T00:00:00Z"};const x=aggregateTopics([{...b,id:"1",status:"failed_gemma",stage:"gemma_stage1"},{...b,id:"2",created_at:"2026-09-20T00:01:00Z",status:"new_topic"},{article_id:"b",id:"3",created_at:"2026-09-20T00:02:00Z",status:"excluded"}]);assert.equal(x.total,2);assert.equal(x.outcomes.new_topic.count,1);assert.equal(x.outcomes.excluded.count,1);assert.equal(x.outcomes.failed_gemma.count,0);});
test("Stage rates use attempt rows; duration statistics use the same observed values",()=>{const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",status:"new_topic",stage:"gemma_stage1",gemma_api_completed:true,gemma_api_duration_ms:10,gemma_prompt_tokens:5},{article_id:"a",id:"2",created_at:"2026-09-20T00:00:01Z",status:"failed_gemma",stage:"gemma_stage1",gemma_http_status:503,gemma_api_duration_ms:30,error_type:"timeout"}]);assert.equal(x.gemma.stage1.total,2);assert.equal(x.gemma.stage1.success,1);assert.equal(x.gemma.stage1.failed,1);assert.equal(x.gemma.stage1.successRate,.5);assert.equal(x.gemma.stage1.averageDurationMs,20);assert.equal(x.gemma.stage1.p95DurationMs,30);assert.equal(x.gemma.stage1.httpFailures[503],1);assert.equal(x.gemma.stage1.promptTokens,5);});
test("Stage 1 includes singleton final failures, and MAX_TOKENS with no facts is not API failure",()=>{const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true},{article_id:"b",id:"2",created_at:"2026-09-20T00:00:01Z",stage:"topic_commit",status:"failed_gemma",error_type:"event_too_long"},{article_id:"c",id:"3",created_at:"2026-09-20T00:00:02Z",stage:"gemma_stage2",status:"new_topic",gemma_api_completed:true,gemma_finish_reason:"MAX_TOKENS"},{article_id:"c",id:"4",created_at:"2026-09-20T00:00:03Z",stage:"topic_commit",status:"new_topic",fact_count:0}]);assert.deepEqual({total:x.gemma.stage1.total,success:x.gemma.stage1.success,failed:x.gemma.stage1.failed},{total:2,success:1,failed:1});assert.deepEqual({total:x.gemma.stage2.total,success:x.gemma.stage2.success,failed:x.gemma.stage2.failed,maxTokens:x.gemma.stage2.maxTokens,maxTokensNoFacts:x.gemma.stage2.maxTokensNoFacts},{total:1,success:1,failed:0,maxTokens:1,maxTokensNoFacts:1});});
test("embedding model and version remain separate; missing metrics remain null",()=>{const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",status:"new_topic",stage:"embedding",embedding_model:null,embedding_version:"modelname:384:v1",similarity:.8},{article_id:"b",id:"2",created_at:"2026-09-20T00:00:01Z",status:"failed_embedding",stage:"embedding",embedding_model:"model-b",embedding_version:"v2",error_type:"timeout"}]);assert.equal(x.embedding.byModelVersion.length,2);assert.equal(x.embedding.byModelVersion.find(r=>r.version==="modelname:384:v1").model,null);assert.equal(x.embedding.byModelVersion.find(r=>r.version==="v2").model,"model-b");assert.equal(x.fallback.count,null);assert.equal(x.fallback.rate,null);assert.equal(x.articleBody.success,null);});
test("empty data and percentile",()=>{const x=aggregateTopics([]);assert.equal(x.total,0);assert.equal(x.gemma.stage1.successRate,null);assert.equal(x.embedding.averageSimilarity,null);assert.equal(x.fallback.rate,null);assert.equal(percentile([1,2,3,4,5],.95),5);});
test("RSS/NewsData aggregation handles empty and populated records",()=>{const d=aggregateNewsData([],jstTodayStart(new Date("2026-09-20T00:00:00Z")));assert.equal(d.todayRequests,0);assert.equal(d.newRate,null);});
test("Supabase logs are paged and capped",async()=>{const old=global.fetch;const offsets=[];global.fetch=async u=>{const off=Number(new URL(u).searchParams.get("offset"));offsets.push(off);const size=off===2000?158:1000;return{ok:true,json:async()=>Array.from({length:size},(_,i)=>({article_id:String(off+i)}))};};try{const rows=await supabaseTopicRows({supabaseUrl:"https://example.test",serviceRole:"x"},new Date("2026-09-19T00:00:00Z"));assert.equal(rows.length,2158);assert.deepEqual(offsets,[0,1000,2000]);}finally{global.fetch=old;}});
test("connection failures preserve other dashboard data and expose no credential values",async()=>{const {dashboardData}=require("./server.js"),old=global.fetch;global.fetch=async()=>{const e=new TypeError("fetch failed");e.cause={code:"ECONNRESET",name:"SocketError"};throw e;};try{const d=await dashboardData();assert.equal(d.connections.supabase.status,"error");assert.equal(d.connections.redis.status,"error");assert.equal(d.overall.status,"unavailable");assert.equal(d.connections.supabase.error.code,"ECONNRESET");}finally{global.fetch=old;}});

test("Topic pregen diagnostic uses a server-side Bearer GET and returns only an allowlist",async()=>{const {topicPregenStatus}=require("./server.js");let requested;const testSecret="test-only-diagnostic-secret";const result=await topicPregenStatus(async(url,options)=>{requested={url:String(url),options};return{ok:true,status:200,json:async()=>({topic_id:"38fd9edf-5d7d-4449-aae9-b4d390d3a259",generation:3,completed_generation:2,attempts:4,rolling_window_attempts:2,status:"retry_wait",last_http_status:503,last_error_type:"http_error",last_error_message:"Unsupported setting <script> key=AIza12345678901234567890 Bearer hidden",retry_not_before:1790320000000,alarm_scheduled:true,alarm_at:1790320000000,parser_succeeded:null,save_attempted:false,save_succeeded:null,last_attempt_at:1790319000000,completed_at:null,title:"must-not-leak",facts:["must-not-leak"]})};},{workerUrl:"https://worker.example/",diagnosticSecret:testSecret});assert.equal(requested.url,"https://worker.example/internal/status");assert.equal(requested.options.method,"GET");assert.ok(requested.options.headers.Authorization===`Bearer ${testSecret}`);assert.equal(Object.hasOwn(requested.options.headers,"apikey"),false);assert.equal(result.available,true);assert.equal(result.state.generation,3);assert.equal(result.state.status,"retry_wait");assert.equal(result.state.lastHttpStatus,503);assert.equal(result.state.lastErrorMessage,"Unsupported setting <script> key=[redacted] Bearer [redacted]");assert.equal(result.state.saveSucceeded,null);assert.equal(Object.hasOwn(result.state,"title"),false);assert.equal(JSON.stringify(result).includes(testSecret),false);assert.equal(JSON.stringify(result).includes("hidden"),false);});

test("Topic pregen diagnostic failures do not return upstream bodies or credentials",async()=>{const {topicPregenStatus}=require("./server.js");const result=await topicPregenStatus(async()=>({ok:false,status:403,text:async()=>"upstream secret and response body"}),{workerUrl:"https://worker.example",diagnosticSecret:"test-only-secret"});assert.deepEqual(result.error,{type:"http_error",httpStatus:403});assert.equal(JSON.stringify(result).includes("upstream"),false);assert.equal(JSON.stringify(result).includes("test-only-secret"),false);});

test("Topic search metrics separate API requests from legacy failed_search commit logs",()=>{const x=aggregateTopics([{id:"1",article_id:"a",created_at:"2026-09-20T00:00:00Z",stage:"topic_commit",status:"new_topic",embedding_version:"openai/text-embedding-3-small:1536:v1"},{id:"2",article_id:"b",created_at:"2026-09-20T00:01:00Z",stage:"topic_commit",status:"merged",embedding_version:"gemini-embedding-2:384:v1"},{id:"3",article_id:"c",created_at:"2026-09-20T00:02:00Z",stage:"topic_commit",status:"failed_search",embedding_version:"gemini-embedding-2:384:v1"}]);assert.equal(x.topicSearch.currentMode,null);assert.equal(x.topicSearch.lastObservedMode,"gemini");assert.equal(x.topicSearch.upstash.successfulCommits,1);assert.equal(x.topicSearch.upstash.searchFailures,null);assert.equal(x.topicSearch.upstash.legacyGeminiFailedSearchCommits,1);assert.equal(x.topicSearch.providerUnattributedFailures,0);assert.equal(x.stage1.models[0].success,null);});

test("Outbox monitoring counts pending, processing and stale claims with read-only count requests",async()=>{const calls=[];const counts=["12","3","1"];const result=await supabaseTopicVectorOutbox({supabaseUrl:"https://example.test",serviceRole:"test-secret"},async(url,options)=>{calls.push({url:String(url),options});const index=calls.length-1,count=counts[index];return{ok:true,headers:{get:()=>`0-0/${count}`},json:async()=>index===0?[{topic_id:"00000000-0000-4000-8000-000000000021",updated_at:"2026-09-20T00:05:00Z"}]:index===2?[{topic_id:"00000000-0000-4000-8000-000000000022",claimed_at:"2026-09-19T23:59:00Z"}]:[]};},new Date("2026-09-20T00:15:00Z"));assert.deepEqual({pending:result.pending,processing:result.processing,staleClaimed:result.staleClaimed,syncFailures:result.syncFailures,oldestPendingAt:result.oldestPendingAt,oldestPendingWaitMinutes:result.oldestPendingWaitMinutes,oldestStaleClaimAt:result.oldestStaleClaimAt},{pending:12,processing:3,staleClaimed:1,syncFailures:null,oldestPendingAt:"2026-09-20T00:05:00Z",oldestPendingWaitMinutes:10,oldestStaleClaimAt:"2026-09-19T23:59:00Z"});assert.equal(calls.length,3);assert.ok(calls.every(x=>x.options.headers.Prefer==="count=exact"&&x.options.headers.Range==="0-0"));assert.match(calls[2].url,/claimed_at=lt\.2026-09-20T00%3A00%3A00.000Z/);assert.equal(JSON.stringify(result).includes("test-secret"),false);});
test("embedding model is derived from a recognized recorded version when the model column is empty",()=>{const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",stage:"topic_commit",status:"new_topic",embedding_model:null,embedding_version:"openai/text-embedding-3-small:1536:v1"}]);assert.equal(x.embedding.byModelVersion[0].model,"openai/text-embedding-3-small");});

test("Upstash failed_search commit attribution stays separate from API call logs",()=>{const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",stage:"topic_commit",status:"failed_search",embedding_version:"openai/text-embedding-3-small:1536:v1"}]);assert.equal(x.topicSearch.upstash.searchFailures,null);assert.equal(x.topicSearch.upstash.legacyUpstashFailedSearchCommits,1);assert.equal(x.topicSearch.providerUnattributedFailures,0);});
test("observability joins model attempts, search API outcomes, Upstash commits and outbox sync separately",()=>{const {aggregateTopics}=require("./server.js"),version="openai/text-embedding-3-small:1536:v1",b="batch-current";const topics=[{id:"s1",article_id:"a1",batch_id:b,created_at:"2026-09-20T00:00:00Z",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true},{id:"s2",article_id:"a2",batch_id:"batch-old",created_at:"2026-09-20T00:00:01Z",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true},{id:"c1",article_id:"a1",created_at:"2026-09-20T00:00:02Z",stage:"topic_commit",status:"new_topic",embedding_version:version},{id:"c2",article_id:"a2",created_at:"2026-09-20T00:00:03Z",stage:"topic_commit",status:"merged",embedding_version:version}];const logs=[{operation:"stage1_attempt",status:"failure",batch_id:b,model:"qwen/qwen3.8-27b",attempt_no:1,model_role:"primary",error_type:"timeout",timeout_retry:false,created_at:"2026-09-20T00:00:01Z"},{operation:"stage1_attempt",status:"failure",batch_id:b,model:"qwen/qwen3.8-27b",attempt_no:2,model_role:"primary",error_type:"timeout",timeout_retry:true,created_at:"2026-09-20T00:00:02Z"},{operation:"stage1_attempt",status:"success",batch_id:b,model:"openai/gpt-oss-20b",attempt_no:3,model_role:"fallback",fallback_reason:"timeout",created_at:"2026-09-20T00:00:03Z"},{operation:"vector_search",status:"success",batch_id:b,article_id:"a1",embedding_version:version,duration_ms:10,created_at:"2026-09-20T00:00:04Z"},{operation:"vector_search",status:"failure",batch_id:b,article_id:"a2",embedding_version:version,duration_ms:22,error_type:"http_401",created_at:"2026-09-20T00:00:05Z"},{operation:"outbox_sync",status:"success",item_count:2,created_at:"2026-09-20T00:00:06Z"},{operation:"outbox_sync",status:"failure",item_count:0,error_type:"http_503",created_at:"2026-09-20T00:00:07Z"}];const x=aggregateTopics(topics,[],[],logs);assert.deepEqual(x.stage1.models.map(m=>[m.attempts,m.success,m.failed,m.timeoutRetries,m.fallback]),[[2,0,2,1,0],[1,1,0,0,1]]);assert.equal(x.stage1.fallbackCount,1);assert.equal(x.stage1.fallbackReasons.timeout,1);assert.equal(x.stage1.unattributedStageRecords,1);assert.equal(x.topicSearch.upstash.searchSuccesses,1);assert.equal(x.topicSearch.upstash.searchFailures,1);assert.equal(x.topicSearch.upstash.searchAverageDurationMs,16);assert.equal(x.topicSearch.upstash.newTopicCommits,1);assert.equal(x.topicSearch.upstash.mergeCommits,1);assert.equal(x.topicOutbox.syncSuccesses,1);assert.equal(x.topicOutbox.syncFailures,1);assert.equal(x.topicOutbox.syncedRecords,2);assert.equal(x.topicOutbox.failureReasons.http_503,1);});
test("observability read pages the existing 24 hour view and exposes no credentials",async()=>{const {supabaseTopicObservabilityRows}=require("./server.js");let call;const rows=await supabaseTopicObservabilityRows({supabaseUrl:"https://example.test",serviceRole:"test-secret"},new Date("2026-09-20T00:00:00Z"),async(url,options)=>{call={url:String(url),options};return{ok:true,json:async()=>[{operation:"vector_search",status:"success"}]};});assert.equal(rows.length,1);assert.equal(new URL(call.url).searchParams.get("created_at"),"gte.2026-09-20T00:00:00.000Z");assert.equal(call.options.headers.Authorization,"Bearer test-secret");assert.equal(JSON.stringify(rows).includes("test-secret"),false);});

test("article body observability reports method, outcomes, text length and duration without article text",()=>{const {aggregateTopics}=require("./server.js");const logs=[{operation:"article_body",status:"success",article_body_method:"readability",article_body_readability:"success",article_body_chars:1200,article_body_redirected:false,duration_ms:800},{operation:"article_body",status:"failure",article_body_method:"readability",article_body_readability:"failed",article_body_chars:0,article_body_redirected:true,error_type:"empty_body",duration_ms:1100}];const x=aggregateTopics([],[],[],logs);assert.equal(x.articleBody.success,1);assert.equal(x.articleBody.failures,1);assert.deepEqual(x.articleBody.method,{readability:2});assert.deepEqual(x.articleBody.failureReasons,{empty_body:1});assert.equal(x.articleBody.chars,600);assert.equal(x.articleBody.durationMs,950);assert.equal(JSON.stringify(x).includes("article body"),false);});

test("dashboard observability query selects only article body metadata",async()=>{const {supabaseTopicObservabilityRows}=require("./server.js");let call;await supabaseTopicObservabilityRows({supabaseUrl:"https://example.test",serviceRole:"test-secret"},new Date("2026-09-20T00:00:00Z"),async(url,options)=>{call={url:String(url),options};return{ok:true,json:async()=>[]};});const select=new URL(call.url).searchParams.get("select");for(const field of ["article_body_method","article_body_readability","article_body_chars","article_body_redirected","diagnostic_details"])assert.ok(select.includes(field));assert.equal(select.split(",").includes("body"),false);});

test("thread title audit read includes request attempts",async()=>{const {supabaseThreadTitleRows}=require("./server.js");const calls=[];const result=await supabaseThreadTitleRows({supabaseUrl:"https://example.test",serviceRole:"test-secret"},new Date("2026-09-20T00:00:00Z"),async(url,options)=>{calls.push({url:String(url)});return{ok:true,json:async()=>[]};});const batch=new URL(calls.find(x=>x.url.includes("topic_thread_title_batches")).url);assert.ok(batch.searchParams.get("select").includes("attempts"));const queue=new URL(calls.find(x=>x.url.includes("topic_thread_title_queue")).url);assert.match(queue.searchParams.get("or"),/queued_at\.gte/);assert.match(queue.searchParams.get("or"),/status\.in/);assert.equal(calls.length,2);assert.equal(JSON.stringify(result).includes("test-secret"),false);});

test("Stage failure and its commit are counted once, with separate stage reasons",()=>{
 const base={article_id:"a",batch_id:"b",created_at:"2026-09-29T00:00:00Z",status:"failed_gemma",error_type:"quota_unavailable"};
 const x=aggregateTopics([{...base,stage:"gemma_stage1"},{...base,stage:"topic_commit"},{...base,article_id:"c",batch_id:"d",stage:"gemma_stage2",error_type:"incomplete_stream"}]);
 assert.equal(x.gemma.stage1.total,1);assert.equal(x.gemma.stage1.failed,1);
 assert.deepEqual(x.gemma.stage1.failureReasons,{quota_unavailable:1});
 assert.deepEqual(x.gemma.stage2.failureReasons,{incomplete_stream:1});
 assert.deepEqual(x.gemma.failuresByReason,{incomplete_stream:1,quota_unavailable:1});
});
test("release audit separates stage outcomes from API attempts by deployed version",()=>{
 const {topicReleaseAudit}=require("./server.js");
 const since=new Date("2026-09-28T01:15:00Z"),now=new Date("2026-09-29T07:30:00Z");
 const rows=[
  {article_id:"a",batch_id:"a",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true,created_at:"2026-09-28T23:00:00Z"},
  {article_id:"b",batch_id:"b",stage:"topic_commit",status:"failed_gemma",error_type:"quota_limit",created_at:"2026-09-29T00:06:00Z"},
  {article_id:"c",batch_id:"c",stage:"gemma_stage2",status:"failed_gemma",error_type:"http_5xx",gemma_http_status:500,created_at:"2026-09-29T04:05:00Z"},
  {article_id:"d",batch_id:"d",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true,created_at:"2026-09-29T05:55:00Z"},
  {article_id:"e",batch_id:"e",stage:"gemma_stage2",status:"new_topic",gemma_api_completed:true,created_at:"2026-09-29T06:15:00Z"},
  {article_id:"f",batch_id:"f",stage:"gemma_stage1",status:"failed_gemma",error_type:"quota_limit",created_at:"2026-09-29T06:22:00Z"},
  {article_id:"g",batch_id:"g",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true,created_at:"2026-09-29T07:05:00Z"},
 ];
 const attempts=[
  {operation:"stage1_attempt",model:"qwen/qwen3.8-27b",status:"success",http_status:200,created_at:"2026-09-28T23:00:00Z"},
  {operation:"stage1_attempt",model:"qwen/qwen3.8-27b",status:"failure",error_type:"quota_limit",created_at:"2026-09-29T00:06:00Z"},
  {operation:"stage1_attempt",model:"openai/gpt-oss-20b",status:"success",http_status:200,created_at:"2026-09-29T05:55:00Z"},
  {operation:"stage1_attempt",model:"openai/gpt-oss-20b",status:"failure",error_type:"quota_limit",created_at:"2026-09-29T06:22:00Z"},
  {operation:"stage1_attempt",model:"qwen/qwen3.8-27b",status:"success",http_status:200,created_at:"2026-09-29T07:05:00Z"},
 ];
 const versions=topicReleaseAudit(since,now,rows,[],[],attempts);
 assert.deepEqual(versions.map(x=>x.version),["v83以前","v83","v84","v85","v86","v87","v88"]);
 assert.equal(versions[0].stage1.success,1);assert.equal(versions[0].stage1Attempts,1);
 assert.equal(versions[1].stage1.failed,1);assert.equal(versions[1].stage1Attempts,1);assert.equal(versions[1].stage1QuotaBlocked,1);
 assert.equal(versions[2].stage2.failed,1);
 assert.equal(versions[3].stage1.success,1);assert.equal(versions[3].stage1Attempts,1);
 assert.equal(versions[4].stage2.success,1);
 assert.equal(versions[5].stage1.failed,1);assert.equal(versions[5].stage1Attempts,1);assert.equal(versions[5].stage1QuotaBlocked,1);
 assert.equal(versions[6].stage1.success,1);assert.equal(versions[6].stage1Attempts,1);
});
test("new models and local quota blocks are visible without claiming API sends",()=>{
 const x=aggregateTopics([],[],[],[{operation:"stage1_attempt",model:"future-model",status:"failure",error_type:"quota_unavailable"},{operation:"stage1_attempt",model:"future-model",status:"failure",error_type:"request_failed"},{operation:"stage1_attempt",model:"future-model",status:"success",http_status:200}]);
 assert.equal(x.stage1.models.length,1);const m=x.stage1.models[0];assert.equal(m.model,"future-model");assert.equal(m.attempts,3);assert.equal(m.quotaBlocked,1);assert.equal(m.httpResponses,1);assert.equal(m.sendUnknown,1);
});

test("unattributed model fallback stays generic instead of naming old model defaults",()=>{
 const x=aggregateTopics([{article_id:"a",id:"1",created_at:"2026-09-20T00:00:00Z",stage:"gemma_stage1",status:"new_topic",gemma_api_completed:true}]);assert.equal(x.stage1.models[0].model,"モデル未記録");
});

test("common diagnostics group counted errors by feature and leave absent cause data unrecorded",()=>{const {aggregateDashboardDiagnostics}=require("./server.js");const groups=aggregateDashboardDiagnostics([{timestamp:"2026-09-20T00:00:00Z",subsystem:"Article body",stage:"article_body",errorType:"http_403",httpStatus:403},{timestamp:"2026-09-20T00:01:00Z",subsystem:"Article body",stage:"article_body",errorType:null,httpStatus:null}]);assert.equal(groups.length,1);assert.equal(groups[0].errorCount,2);assert.equal(groups[0].lastOccurredAt,"2026-09-20T00:01:00Z");assert.equal(groups[0].events[0].confirmedCause,null);assert.equal(groups[0].events[0].retry,null);assert.equal(groups[0].events[0].finalResult,null);});
test("diagnostic events expose safe article, quota, network and stage details while old rows remain unrecorded",()=>{
 const {buildDashboardDiagnosticEvents,aggregateDashboardDiagnostics}=require("./server.js");
 const events=buildDashboardDiagnosticEvents({observabilityRows:[
  {operation:"article_body",status:"failure",article_id:"https://news.example/a?token=secret",http_status:403,error_type:"http_403",article_body_readability:"not_run",article_body_chars:0,article_body_redirected:false,created_at:"2026-09-29T08:00:00Z",diagnostic_details:{domain:"news.example",finalDomain:"news.example",domParse:"not_run",retryCount:0,finalExclusionReason:"http_403"}},
  {operation:"stage1_attempt",status:"failure",batch_id:"00000000-0000-4000-8000-000000000001",model:"qwen/qwen3.8-27b",error_type:"timeout",created_at:"2026-09-29T08:01:00Z",diagnostic_details:{provider:"groq",model:"qwen/qwen3.8-27b",apiSendState:"send_attempted_no_response",transportErrorType:"timeout",quota:{scope:"groq",reason:"quota_limit",axis:"minute",window:"60s rolling",limit:10,used:8,requested:2,reserved:1,nextAvailableAt:"2026-09-29T08:02:00Z"}}},
  {operation:"article_body",status:"failure",article_id:"safe-id",error_type:"readability_failed",created_at:"2026-09-29T08:02:00Z"},
 ]});
 const body=events.find(e=>e.feature==="記事本文取得"&&e.identifiers.articleId.startsWith("sha256:"));
 assert.equal(body.displayDetails.domain,"news.example");assert.equal(body.displayDetails.finalExclusionReason,"http_403");
 const stage=events.find(e=>e.feature==="Stage 1");assert.equal(stage.displayDetails.quotaReason,"quota_limit");assert.equal(stage.displayDetails.quotaAxis,"minute");assert.equal(stage.displayDetails.quotaWindow,"60s rolling");assert.equal(stage.displayDetails.quotaRequested,2);assert.equal(stage.displayDetails.quotaReserved,1);assert.equal(stage.displayDetails.transportErrorType,"timeout");
 assert.equal(JSON.stringify(events).includes("token=secret"),false);
 const groups=aggregateDashboardDiagnostics(events);assert.equal(groups.find(g=>g.feature==="Stage 1").errorCount,1);
 assert.equal(groups.find(g=>g.feature==="記事本文取得").events.find(e=>e.identifiers.articleId==="safe-id").deploymentVersion,"v88");
});

test("title batches distinguish retries, failed Topic counts, and deployment recurrence",()=>{
 const {buildDashboardDiagnosticEvents,aggregateDashboardDiagnostics}=require("./server.js");
 const old=buildDashboardDiagnosticEvents({observabilityRows:[{operation:"stage1_attempt",status:"failure",model:"qwen/qwen3.8-27b",error_type:"timeout",batch_id:"old",created_at:"2026-09-29T00:30:00Z"}]});
 assert.equal(aggregateDashboardDiagnostics(old)[0].classification,"過去の問題");
 const current=buildDashboardDiagnosticEvents({observabilityRows:[{operation:"stage1_attempt",status:"failure",model:"qwen/qwen3.8-27b",error_type:"timeout",batch_id:"new",created_at:"2026-09-29T11:58:00Z"}]});
 assert.equal(current[0].deploymentVersion,"v90");
 assert.equal(aggregateDashboardDiagnostics(current)[0].classification,"要対応");
 const title=buildDashboardDiagnosticEvents({titleBatches:[{id:"00000000-0000-4000-8000-000000000002",created_at:"2026-09-29T08:00:00Z",http_status:504,attempts:2,batch_size:4,failure_count:2,success_count:2,failure_types:{timeout:2}}],titleRows:[{claim_id:"00000000-0000-4000-8000-000000000002",topic_id:"00000000-0000-4000-8000-000000000003"}]});
 assert.equal(title[0].count,2);assert.equal(title[0].httpStatus,504);assert.equal(title[0].retry,"1回（全attempt 2回）");assert.match(title[0].identifiers.topicIds,/00000000-0000-4000-8000-000000000003/);
});

test("processing monitor avoids declaring an idle queue stopped and reports only elapsed schedules or stale claims",()=>{
 const {summarizeTopicProcessingQueue,buildProcessingMonitorEvents}=require("./server.js"),now=new Date("2026-09-29T10:00:00Z");
 const queue=summarizeTopicProcessingQueue([{article_id:"a",queued_at:"2026-09-29T09:58:00Z",claimed_at:null,processed_at:null,terminal_status:null}],now);
 assert.equal(queue.pending,1);assert.equal(queue.processing,0);assert.equal(queue.monitorState,"監視情報不足");
 assert.deepEqual(buildProcessingMonitorEvents({queue,newsdata:{lastExecutionAt:null},schedule:{nextFetchAt:"2026-09-29T11:00:00Z"},now}),[]);
 const stale=summarizeTopicProcessingQueue([{article_id:"b",queued_at:"2026-09-29T09:00:00Z",claimed_at:"2026-09-29T09:30:00Z",external_api_started_at:null,processed_at:null,terminal_status:null}],now);
 assert.equal(stale.staleClaims,1);
 assert.equal(buildProcessingMonitorEvents({queue:stale,newsdata:{lastExecutionAt:"2026-09-29T06:00:00Z"},schedule:{nextFetchAt:"2026-09-29T07:00:00Z",cronIntervalMinutes:60},now}).length,2);
});

test("Stage 2 retry observations distinguish recovered, deferred, and final failures",()=>{
 const {buildDashboardDiagnosticEvents,aggregateDashboardDiagnostics,aggregateTopicObservability}=require("./server.js");
 const rows=[
  {operation:"stage2_attempt",status:"failure",article_id:"recovered",batch_id:"b1",attempt_no:1,http_status:500,error_type:"http_500",created_at:"2026-09-29T08:00:00Z",diagnostic_details:{retryCount:1,firstHttpError:{status:500},finalResult:"success",finalHttpStatus:200}},
  {operation:"stage2_attempt",status:"success",article_id:"recovered",batch_id:"b1",attempt_no:2,http_status:200,created_at:"2026-09-29T08:00:01Z",diagnostic_details:{retryCount:1,finalResult:"success",finalHttpStatus:200}},
  {operation:"stage2_attempt",status:"failure",article_id:"deferred",batch_id:"b2",attempt_no:1,http_status:429,error_type:"http_429",created_at:"2026-09-29T08:01:00Z",diagnostic_details:{retryCount:0,rateLimitType:"rpd",scheduledAt:"2026-09-30T07:00:00Z",finalResult:"deferred",finalHttpStatus:429}},
  {operation:"stage2_attempt",status:"failure",article_id:"failed",batch_id:"b3",attempt_no:4,http_status:503,error_type:"http_503",created_at:"2026-09-29T08:02:00Z",diagnostic_details:{retryCount:3,quotaRetryStopped:true,finalResult:"failure",finalHttpStatus:503}},
 ];
 const events=buildDashboardDiagnosticEvents({observabilityRows:rows});
 const recovered=events.find(e=>e.identifiers.articleId==="recovered");
 const deferred=events.find(e=>e.identifiers.articleId==="deferred");
 const failed=events.find(e=>e.identifiers.articleId==="failed");
 assert.equal(recovered.retrySucceeded,true);assert.match(recovered.finalResult,/200/);assert.equal(recovered.retry,"1回");
 assert.equal(deferred.retrySucceeded,true);assert.match(deferred.finalResult,/2026-09-30T07:00:00Z/);assert.equal(deferred.displayDetails.rateLimitType,"rpd");
 assert.equal(failed.retrySucceeded,false);assert.equal(failed.displayDetails.quotaRetryStopped,true);assert.equal(failed.displayDetails.finalHttpStatus,503);
 assert.equal(aggregateDashboardDiagnostics(events).find(g=>g.feature==="Stage 2 / Gemma 4 26B").errorCount,3);
 const summary=aggregateTopicObservability(rows);assert.equal(summary.stage2.failures,1);assert.equal(summary.stage2.recoveredAttempts,1);assert.equal(summary.stage2.deferredAttempts,1);
});

test("processing queue reports the next deferred Stage 2 schedule",()=>{
 const {summarizeTopicProcessingQueue}=require("./server.js"),now=new Date("2026-09-29T10:00:00Z");
 const queue=summarizeTopicProcessingQueue([
  {article_id:"a",queued_at:"2026-09-29T08:00:00Z",available_at:"2026-09-29T12:00:00Z",stage2_attempt_count:1,claimed_at:null,processed_at:null,terminal_status:null},
  {article_id:"b",queued_at:"2026-09-29T09:00:00Z",available_at:null,stage2_attempt_count:0,claimed_at:null,processed_at:null,terminal_status:null},
 ],now);
 assert.equal(queue.pending,2);assert.equal(queue.deferred,1);assert.equal(queue.nextScheduledAt,"2026-09-29T12:00:00Z");
});

test("NewsData diagnostic events retain safe HTTP, request mode, execution and success times",()=>{
 const now=Date.now(),{aggregateNewsData}=require("./server.js"),start=new Date(now-60000).toISOString();
 const result=aggregateNewsData([{run_id:"00000000-0000-4000-8000-000000000004",run_started_at:start,run_finished_at:start,successful_requests:0,stopped_by_error:true,error_type:"timeout",error_status:504,error_request_index:1,requests:[{request_index:1,request_mode:"normal",started_at:start,status:"error",error_type:"timeout",error_status:504,network_category:"timeout"}]}],new Date(now-86400000));
 assert.equal(result.diagnosticEvents.length,1);assert.equal(result.diagnosticEvents[0].httpStatus,504);assert.equal(result.diagnosticEvents[0].requestMode,"normal");assert.equal(result.lastExecutionAt,start);assert.equal(result.lastSuccessAt,null);
 assert.equal(JSON.stringify(result.diagnosticEvents).includes("url"),false);
});
test("31B status allowlist exposes parser, provider and save states without returned content",()=>{
 const {safeTopicPregenState}=require("./server.js");
 const result=safeTopicPregenState({topic_id:"00000000-0000-4000-8000-000000000010",generation:115,status:"failed",attempts:2,last_http_status:503,provider_http_status:200,save_http_status:null,last_diagnostic_phase:"model_json",sse_read_completed:true,sse_completion_confirmed:true,sse_end_marker_seen:false,model_finish_reason:"STOP",comment_count:9,comment_validation_reason:"comment_count_too_few",parser_succeeded:false,save_attempted:false,title:"private title",facts:["private fact"],generated_text:"private response"},"2026-09-29T08:00:00Z");
 assert.equal(result.state.providerHttpStatus,200);assert.equal(result.state.lastHttpStatus,503);assert.equal(result.state.lastDiagnosticPhase,"model_json");assert.equal(result.state.sseCompletionConfirmed,true);assert.equal(result.state.modelFinishReason,"STOP");assert.equal(result.state.commentCount,9);assert.equal(result.state.commentValidationReason,"comment_count_too_few");
 const json=JSON.stringify(result);assert.equal(json.includes("private title"),false);assert.equal(json.includes("private fact"),false);assert.equal(json.includes("private response"),false);
});

test("processing queue query includes active items and recent completions in the existing read",async()=>{
 const {supabaseProcessingQueueRows}=require("./server.js");let call;
 const old=global.fetch;global.fetch=async(url)=>{call=String(url);return{ok:true,json:async()=>[{article_id:"active",processed_at:null,queued_at:"2026-09-29T00:00:00Z"}]};};try{const rows=await supabaseProcessingQueueRows({supabaseUrl:"https://example.test",serviceRole:"test-secret"},new Date("2026-09-28T00:00:00Z"));assert.equal(rows.length,1);const query=new URL(call);assert.match(query.searchParams.get("or"),/processed_at\.gte/);assert.match(query.searchParams.get("or"),/processed_at\.is\.null/);assert.ok(query.searchParams.get("select").includes("external_api_started_at"));assert.ok(query.searchParams.get("select").includes("available_at"));assert.ok(query.searchParams.get("select").includes("stage2_attempt_count"));assert.equal(JSON.stringify(rows).includes("test-secret"),false);}finally{global.fetch=old;}
});
test("stale Outbox claims are actionable and include safe target and backlog age",()=>{
 const {buildProcessingMonitorEvents}=require("./server.js"),now=new Date("2026-09-29T10:00:00Z");
 const events=buildProcessingMonitorEvents({queue:{pending:0,processing:0,staleClaims:0,staleExternalCalls:0},newsdata:{lastExecutionAt:null},schedule:{nextFetchAt:"2026-09-29T11:00:00Z"},outbox:{pending:8,processing:2,staleClaimed:1,oldestStaleClaimAt:"2026-09-29T09:40:00Z",oldestStaleTopicId:"00000000-0000-4000-8000-000000000023",oldestPendingWaitMinutes:22},now});
 assert.equal(events.length,1);assert.equal(events[0].feature,"Vector Outbox");assert.equal(events[0].identifiers.topicId,"00000000-0000-4000-8000-000000000023");assert.equal(events[0].displayDetails.oldestPendingWaitMinutes,22);
});
