import { config } from "./config.ts";

export function cronScheduleFromInterval(intervalSeconds: number): string {
  if (
    !Number.isSafeInteger(intervalSeconds) || intervalSeconds <= 0 ||
    intervalSeconds % 60 !== 0
  ) {
    throw new Error("Cron interval must be a positive whole number of minutes");
  }

  const intervalMinutes = intervalSeconds / 60;
  if (intervalMinutes <= 60 && 60 % intervalMinutes === 0) {
    return intervalMinutes === 1 ? "* * * * *" : `*/${intervalMinutes} * * * *`;
  }

  const intervalHours = intervalMinutes / 60;
  if (
    Number.isInteger(intervalHours) && intervalHours > 0 &&
    24 % intervalHours === 0
  ) {
    return intervalHours === 1 ? "0 * * * *" : `0 */${intervalHours} * * *`;
  }

  throw new Error(
    "Cron interval cannot be represented as a daily repeating schedule",
  );
}

export function generateCronSql(
  schedule = cronScheduleFromInterval(config.intervalSeconds),
): string {
  return `-- Generated by _shared/newsdata/generate_cron.ts. Do not edit schedule here.
-- Prerequisites: pg_cron, pg_net, Vault; deployed update-newsdata (--no-verify-jwt).
-- Vault names: project_url, newsdata_job_secret (same value as NEWSDATA_JOB_SECRET).
-- Inspect live jobs first; this file changes only the named NewsData job.
do $$
begin
  if to_regclass('cron.job') is null then
    raise exception 'NewsData Cron prerequisites missing: enable pg_cron first';
  end if;
  if to_regnamespace('net') is null then
    raise exception 'NewsData Cron prerequisites missing: enable pg_net first';
  end if;
  if to_regclass('vault.decrypted_secrets') is null or
    not exists (select 1 from vault.decrypted_secrets where name = 'project_url') or
    not exists (select 1 from vault.decrypted_secrets where name = 'newsdata_job_secret') then
    raise exception 'NewsData Cron Vault prerequisites missing: project_url and newsdata_job_secret';
  end if;
end;
$$;
select jobid, jobname, schedule, active
from cron.job
where jobname = 'update-newsdata';
do $$
declare
  v_job_id bigint;
  v_job_count integer;
begin
  select count(*), min(jobid)
    into v_job_count, v_job_id
  from cron.job
  where jobname = 'update-newsdata';

  if v_job_count > 1 then
    raise exception 'Multiple update-newsdata cron jobs found: %', v_job_count;
  elsif v_job_count = 1 then
    perform cron.alter_job(job_id := v_job_id, schedule := '${schedule}', active := true);
  else
    perform cron.schedule(
      'update-newsdata', '${schedule}',
      $job$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url') || '/functions/v1/update-newsdata',
    headers := jsonb_build_object('Content-Type', 'application/json',
      'x-newsdata-job-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'newsdata_job_secret')),
    body := '{"trigger":"cron"}'::jsonb,
    timeout_milliseconds := 120000
  );
      $job$
    );
  end if;
end;
$$;
select jobid, jobname, schedule, active
from cron.job
where jobname = 'update-newsdata';
do $$
declare
  v_job_count integer;
  v_is_expected_active boolean;
begin
  select count(*), bool_and(schedule = '${schedule}' and active)
    into v_job_count, v_is_expected_active
  from cron.job
  where jobname = 'update-newsdata';

  if v_job_count <> 1 or not coalesce(v_is_expected_active, false) then
    raise exception 'update-newsdata cron verification failed (count %, expected schedule active %)',
      v_job_count, v_is_expected_active;
  end if;
end;
$$;
-- RSS Cron remains separate. Verify its live schedule is */15 * * * *.
-- If its name is update-news-cache, apply the following after checking the live job:
-- select cron.alter_job(job_id := (select jobid from cron.job where jobname = 'update-news-cache'), schedule := '*/15 * * * *');
`;
}

if (import.meta.main) {
  await Deno.mkdir("supabase/sql", { recursive: true });
  await Deno.writeTextFile("supabase/sql/newsdata_cron.sql", generateCronSql());
}
