alter table public.thread_chunks
  add column if not exists conversation_pattern text;
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'thread_chunks_conversation_pattern_check'
      and conrelid = 'public.thread_chunks'::regclass
  ) then
    alter table public.thread_chunks
      add constraint thread_chunks_conversation_pattern_check
      check (
        conversation_pattern is null or conversation_pattern in (
          'independent',
          'singleReply',
          'doubleReply',
          'chain3',
          'branch',
          'mixed'
        )
      );
  end if;
end
$$;
create table if not exists public.ai_chunk_engagement_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id uuid not null,
  article_id bigint not null references public.articles(id) on delete cascade,
  chunk_index integer not null check (chunk_index > 0),
  conversation_pattern text not null check (
    conversation_pattern in (
      'independent',
      'singleReply',
      'doubleReply',
      'chain3',
      'branch',
      'mixed'
    )
  ),
  conversation_density real not null check (
    conversation_density >= 0 and conversation_density <= 1
  ),
  event_type text not null check (
    event_type in ('chunk_start', 'chunk_end', 'anchor_tap', 'user_post')
  ),
  category text check (
    category is null or category in (
      'トレンド',
      'エンタメ',
      'スポーツ',
      'サブカル',
      'マネー',
      'IT・ガジェット',
      'マイRSS'
    )
  ),
  unique (session_id, article_id, chunk_index, event_type)
);
alter table public.ai_chunk_engagement_events enable row level security;
revoke all on table public.ai_chunk_engagement_events from anon, authenticated;
create or replace function public.record_ai_chunk_engagement(
  p_session_id uuid,
  p_news_url text,
  p_chunk_index integer,
  p_event_type text,
  p_category text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_article_id bigint;
  target_pattern text;
  target_replies jsonb;
  reply_count integer;
  relation_count integer;
  participant_count integer;
  relations_match_pattern boolean;
  target_density real;
begin
  if p_chunk_index <= 0 or
     p_event_type not in ('chunk_start', 'chunk_end', 'anchor_tap', 'user_post') or
     (p_category is not null and p_category not in (
       'トレンド', 'エンタメ', 'スポーツ', 'サブカル',
       'マネー', 'IT・ガジェット', 'マイRSS'
     )) then
    return;
  end if;

  select a.id, tc.conversation_pattern, tc.replies
    into target_article_id, target_pattern, target_replies
  from public.articles a
  join public.thread_chunks tc on tc.article_id = a.id
  where a.news_url = p_news_url
    and tc.chunk_index = p_chunk_index
    and tc.conversation_pattern is not null
  limit 1;

  if target_article_id is null then
    return;
  end if;

  reply_count := jsonb_array_length(target_replies);
  if reply_count = 0 then
    return;
  end if;

  -- Malformed or out-of-range relations must never be measured. The pattern and
  -- density below are derived only from the stored thread chunk, never from RPC
  -- arguments supplied by the client.
  if exists (
    select 1
    from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
    where value -> 'replyTo' is not null
      and (
        jsonb_typeof(value -> 'replyTo') <> 'number' or
        (value ->> 'replyTo') !~ '^[0-9]+$' or
        (value ->> 'replyTo')::integer < 1 or
        (value ->> 'replyTo')::integer > reply_count or
        (value ->> 'replyTo')::integer = ordinality::integer
      )
  ) then
    return;
  end if;

  with relations as (
    select
      ordinality::integer as source,
      (value ->> 'replyTo')::integer as target
    from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
    where value -> 'replyTo' is not null
  ), participants as (
    select source as participant from relations
    union
    select target as participant from relations
  )
  select
    (select count(*)::integer from relations),
    count(*)::integer
  into relation_count, participant_count
  from participants;

  relations_match_pattern := case target_pattern
    when 'independent' then relation_count = 0
    when 'singleReply' then relation_count = 1 and participant_count = 2
    when 'doubleReply' then relation_count = 2 and participant_count = 4
    when 'chain3' then relation_count = 2 and participant_count = 3 and exists (
      select 1
      from (
        select
          ordinality::integer as source,
          (value ->> 'replyTo')::integer as target
        from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
        where value -> 'replyTo' is not null
      ) first_relation
      cross join (
        select
          ordinality::integer as source,
          (value ->> 'replyTo')::integer as target
        from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
        where value -> 'replyTo' is not null
      ) second_relation
      where first_relation.source < second_relation.source
        and (
          first_relation.source = second_relation.target or
          second_relation.source = first_relation.target
        )
    )
    when 'branch' then relation_count = 2 and participant_count = 3 and (
      select count(distinct (value ->> 'replyTo')::integer) = 1
      from jsonb_array_elements(target_replies) as reply(value)
      where value -> 'replyTo' is not null
    )
    when 'mixed' then relation_count = 3 and participant_count = 5 and exists (
      select 1
      from (
        select
          ordinality::integer as source,
          (value ->> 'replyTo')::integer as target
        from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
        where value -> 'replyTo' is not null
      ) first_relation
      cross join (
        select
          ordinality::integer as source,
          (value ->> 'replyTo')::integer as target
        from jsonb_array_elements(target_replies) with ordinality as reply(value, ordinality)
        where value -> 'replyTo' is not null
      ) second_relation
      where first_relation.source < second_relation.source
        and (
          first_relation.source = second_relation.target or
          second_relation.source = first_relation.target
        )
    )
    else false
  end;

  if not relations_match_pattern then
    return;
  end if;

  target_density := coalesce(participant_count, 0)::real / reply_count::real;

  insert into public.ai_chunk_engagement_events (
    session_id,
    article_id,
    chunk_index,
    conversation_pattern,
    conversation_density,
    event_type,
    category
  ) values (
    p_session_id,
    target_article_id,
    p_chunk_index,
    target_pattern,
    target_density,
    p_event_type,
    p_category
  )
  on conflict (session_id, article_id, chunk_index, event_type) do nothing;
end;
$$;
revoke all on function public.record_ai_chunk_engagement(uuid, text, integer, text, text)
  from public;
grant execute on function public.record_ai_chunk_engagement(uuid, text, integer, text, text)
  to anon, authenticated;
create or replace view public.ai_conversation_pattern_metrics
with (security_invoker = true)
as
with starts as (
  select
    event.session_id,
    event.article_id,
    event.chunk_index,
    event.conversation_pattern,
    event.conversation_density,
    event.category,
    exists (
      select 1
      from public.ai_chunk_engagement_events next_event
      where next_event.session_id = event.session_id
        and next_event.article_id = event.article_id
        and next_event.chunk_index = event.chunk_index + 1
        and next_event.event_type = 'chunk_start'
    ) as reached_next,
    exists (
      select 1
      from public.ai_chunk_engagement_events end_event
      where end_event.session_id = event.session_id
        and end_event.article_id = event.article_id
        and end_event.chunk_index = event.chunk_index
        and end_event.event_type = 'chunk_end'
    ) as reached_end,
    exists (
      select 1
      from public.ai_chunk_engagement_events anchor_event
      where anchor_event.session_id = event.session_id
        and anchor_event.article_id = event.article_id
        and anchor_event.chunk_index = event.chunk_index
        and anchor_event.event_type = 'anchor_tap'
    ) as tapped_anchor,
    exists (
      select 1
      from public.ai_chunk_engagement_events post_event
      where post_event.session_id = event.session_id
        and post_event.article_id = event.article_id
        and post_event.chunk_index = event.chunk_index
        and post_event.event_type = 'user_post'
    ) as posted
  from public.ai_chunk_engagement_events event
  where event.event_type = 'chunk_start'
)
select
  conversation_pattern,
  conversation_density,
  category,
  count(*) as chunk_starts,
  count(*) filter (where reached_end) as chunk_ends,
  count(*) filter (where reached_end)::double precision / nullif(count(*), 0)
    as chunk_end_rate,
  count(*) filter (where reached_next) as next_chunk_sessions,
  count(*) filter (where reached_next)::double precision / nullif(count(*), 0)
    as next_chunk_rate,
  count(*) filter (where tapped_anchor)::double precision / nullif(count(*), 0)
    as anchor_tap_rate,
  count(*) filter (where posted)::double precision / nullif(count(*), 0)
    as user_post_rate
from starts
group by conversation_pattern, conversation_density, category;
revoke all on table public.ai_conversation_pattern_metrics from anon, authenticated;
