create table public.ai_reply_reports (
  id bigint generated by default as identity primary key,
  report_target_id text not null unique,
  news_url text not null,
  reply_text text not null,
  report_type text not null check (report_type in (
    'dislike_or_display_issue', 'harmful_or_abusive', 'incorrect_content', 'other'
  )),
  note text check (note is null or char_length(note) <= 200),
  updated_at timestamptz not null default now(),
  check (report_type = 'other' or note is null)
);
alter table public.ai_reply_reports enable row level security;
revoke all on table public.ai_reply_reports from anon, authenticated;
-- 書き込み専用。通報本文・自由記述の読み取り権限は公開しない。
create or replace function public.save_ai_reply_report(
  p_report_target_id text,
  p_news_url text,
  p_reply_text text,
  p_report_type text,
  p_note text,
  p_updated_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_report_target_id is null or p_report_target_id = '' then
    raise exception 'Invalid report target';
  end if;
  insert into public.ai_reply_reports (
    report_target_id, news_url, reply_text, report_type, note, updated_at
  ) values (
    p_report_target_id, p_news_url, p_reply_text, p_report_type,
    case when p_report_type = 'other' then p_note else null end, p_updated_at
  )
  on conflict (report_target_id) do update set
    news_url = excluded.news_url,
    reply_text = excluded.reply_text,
    report_type = excluded.report_type,
    note = excluded.note,
    updated_at = excluded.updated_at;
end;
$$;
revoke all on function public.save_ai_reply_report(text, text, text, text, text, timestamptz) from public;
grant execute on function public.save_ai_reply_report(text, text, text, text, text, timestamptz) to anon, authenticated;
