begin;

create table public.articles (
  id bigint generated by default as identity primary key,
  news_url text not null,
  news_title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_accessed_at timestamptz not null default now(),
  constraint articles_news_url_key unique (news_url)
);

create index articles_last_accessed_at_idx
  on public.articles using btree (last_accessed_at);

create table public.thread_chunks (
  id bigint generated by default as identity primary key,
  article_id bigint not null,
  chunk_index integer not null,
  replies jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  conversation_pattern text,
  constraint thread_chunks_article_id_fkey
    foreign key (article_id)
    references public.articles(id)
    on delete cascade,
  constraint thread_chunks_article_id_chunk_index_key
    unique (article_id, chunk_index),
  constraint thread_chunks_chunk_index_check
    check (chunk_index >= 1),
  constraint thread_chunks_conversation_pattern_check
    check (
      conversation_pattern is null or conversation_pattern in (
        'independent',
        'singleReply',
        'doubleReply',
        'chain3',
        'branch',
        'mixed'
      )
    )
);

create index thread_chunks_article_id_idx
  on public.thread_chunks using btree (article_id);

alter table public.articles enable row level security;
alter table public.thread_chunks enable row level security;

revoke all on table public.articles, public.thread_chunks
  from public, anon, authenticated;

grant select (id, news_url), insert (news_url, news_title, updated_at, last_accessed_at),
  update (news_title, updated_at, last_accessed_at)
  on table public.articles to anon, authenticated;
grant select (article_id, chunk_index, replies, conversation_pattern),
  insert (article_id, chunk_index, replies, conversation_pattern, updated_at)
  on table public.thread_chunks to anon, authenticated;

create policy articles_select_shared_cache
  on public.articles for select to anon, authenticated
  using (true);
create policy articles_insert_shared_cache
  on public.articles for insert to anon, authenticated
  with check (true);
create policy articles_update_shared_cache
  on public.articles for update to anon, authenticated
  using (true)
  with check (true);

create policy thread_chunks_select_shared_cache
  on public.thread_chunks for select to anon, authenticated
  using (true);
create policy thread_chunks_insert_shared_cache
  on public.thread_chunks for insert to anon, authenticated
  with check (true);

commit;
