begin;

create table public.topic_observability_logs (
  id bigint generated by default as identity primary key,
  operation text not null check (operation in ('stage1_attempt', 'vector_search', 'outbox_sync')),
  status text not null check (status in ('success', 'failure')),
  batch_id uuid,
  article_id text,
  model text check (model is null or model in ('qwen/qwen3.8-27b', 'openai/gpt-oss-20b')),
  attempt_no smallint check (attempt_no is null or attempt_no between 1 and 3),
  model_role text check (model_role is null or model_role in ('primary', 'fallback')),
  timeout_retry boolean,
  fallback_reason varchar(64),
  embedding_version varchar(100),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  item_count integer check (item_count is null or item_count >= 0),
  error_type varchar(64),
  http_status smallint check (http_status is null or http_status between 100 and 599),
  created_at timestamptz not null default now(),
  constraint topic_observability_logs_payload_check check (
    (operation = 'stage1_attempt' and model is not null and attempt_no is not null and model_role is not null)
    or (operation = 'vector_search' and article_id is not null and embedding_version is not null)
    or (operation = 'outbox_sync' and item_count is not null)
  )
);

create index topic_observability_logs_created_at_idx
  on public.topic_observability_logs(created_at desc);
create index topic_observability_logs_operation_created_idx
  on public.topic_observability_logs(operation, created_at desc);
create index topic_observability_logs_batch_attempt_idx
  on public.topic_observability_logs(batch_id, attempt_no)
  where operation = 'stage1_attempt';

alter table public.topic_observability_logs enable row level security;
revoke all on public.topic_observability_logs from public, anon, authenticated;
grant all on public.topic_observability_logs to service_role;
grant usage, select on sequence public.topic_observability_logs_id_seq to service_role;

select cron.schedule(
  'cleanup-topic-observability-logs',
  '0 3 * * *',
  $job$
    delete from public.topic_observability_logs
      where created_at < now() - interval '7 days';
  $job$
);

commit;
